name: spack

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build-cpu:
    #runs-on: ubuntu-latest
    runs-on: ${{ matrix.os }}
    container: ghcr.io/gridtools/gridtools-base:gcc-9-ucx-mpi
    strategy:
      matrix:
        os: [ubuntu-22.04]
        python-version: ['3.10']
        #spack-version: ['develop', 'latest_release']
        spack-version: ['v0.20.1']
    steps:
      - name: print system info
        shell: bash
        run: |
          echo "USER=${USER}"
          _user="$(id -u -n)"
          echo "user=${_user}"
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: install-ghex-org-packages
        run: |
          mkdir /repos
          git clone https://github.com/ghex-org/spack-repos.git /repos
      - name: spack buildcache
        id: spack-buildcache
        uses: actions/cache@v3
        #env:
        #  cache-name: spack-buildcache_
        with:
          path: |
            /spack_buildcache
            /spack_keys
          key: spack-cache-${{ matrix.os }}-${{ matrix.spack-version }}-${{ github.run_id }}
          restore-keys: spack-cache-${{ matrix.os }}-${{ matrix.spack-version }}-
      - name: install-spack
        shell: bash
        run: |
          mkdir /spack
          git clone --depth 1 --branch ${{ matrix.spack-version }}  https://github.com/spack/spack.git /spack
          mkdir /spack/.cache
          mkdir /spack/.tmp
          echo "config:" > /spack/etc/spack/config.yaml
          echo "  install_tree:" >> /spack/etc/spack/config.yaml
          echo "    padded_length: True" >> /spack/etc/spack/config.yaml
          echo "#!/bin/bash" > /spack/share/spack/my-setup-env.sh
          echo "export SPACK_DISABLE_LOCAL_CONFIG=true" >> /spack/share/spack/my-setup-env.sh
          echo "export SPACK_USER_CACHE_PATH=/spack/.cache" >> /spack/share/spack/my-setup-env.sh
          echo "export TMP=/spack/.tmp" >> /spack/share/spack/my-setup-env.sh
          echo ". /spack/share/spack/setup-env.sh" >> /spack/share/spack/my-setup-env.sh
          . /spack/share/spack/my-setup-env.sh
          #spack compiler find
          spack repo add /repos
      - if: ${{ steps.spack-buildcache.outputs.cache-hit != 'true' }}
        name: create buildcache keys
        shell: bash
        run: |
          mkdir /spack_buildcache
          mkdir /spack_keys
          . /spack/share/spack/my-setup-env.sh
          spack gpg create --export-secret /spack_keys/key.private --export /spack_keys/key.public spack-test spacktest@ghex.org
      - name: import keys and add cache
        shell: bash
        run: |
          . /spack/share/spack/my-setup-env.sh
          spack gpg trust /spack_keys/key.private
          spack mirror add mirror /spack_buildcache
          spack buildcache update-index /spack_buildcache
      - name: build-and-test
        shell: bash
        run: |
          . /spack/share/spack/my-setup-env.sh
          spack spec -I hwmalloc@master
          spack install --test=root hwmalloc@master
          spack buildcache push --only dependencies -a -k spack-test /spack_buildcache hwmalloc@master

