name: spack

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build-cpu:
    runs-on: ubuntu-latest
    container: boeschf/ghex-org
    steps:
      - name: install-ghex-org-packages
        run: |
          sudo mkdir /repos
          sudo chown -R ${USER}:${USER} /repos
          git clone https://github.com/ghex-org/spack-repos.git /repos
          spack repo add /repos
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: hwmalloc
      - name: build-and-test
        run: |
          cd hwmalloc
          spack dev-build --test=root hwmalloc@develop
