name: spack

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build-cpu:
    #runs-on: ubuntu-latest
    runs-on: ${{ matrix.os }}
    #container: ghcr.io/gridtools/gridtools-base:gcc-9-ucx-mpi
    strategy:
      matrix:
        os: [ubuntu-22.04]
        python-version: ['3.10']
        #spack-version: ['develop', 'latest_release']
        spack-version: ['v0.20.1']
    steps:
      - name: print system info
        shell: bash
        run: |
          echo "USER=${USER}"
          _user="$(id -u -n)"
          echo "user=${_user}"
          echo ${{ github.run_id }}
      - name: "Linux: update"
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        run: |
          sudo apt-get update
          #sudo apt-get install -y libopenmpi-dev ninja-build ccache ${{ matrix.config.cc }}
      #- name: "MacOS: update"
      #  if: ${{ startsWith(matrix.config.os, 'macos') }}
      #  run: |
      #    brew install openmpi ninja ccache
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: install-ghex-org-packages
        run: |
          sudo mkdir /repos
          sudo chown -R ${USER}:${USER} /repos
          git clone https://github.com/ghex-org/spack-repos.git /repos
      # figure out vector extensions for cache key
      - if: ${{ contains(matrix.config.os, 'macos') }}
        name: Check vector extensions
        # assume uniform hardware for macos
        run: |
          echo "VECTOR_EXTENSIONS=" >> $GITHUB_ENV
      - if: ${{ contains(matrix.config.os, 'ubuntu') }}
        name: Check vector extensions
        run: |
          HAS_AVX512F=$([[ $(lscpu | grep "avx512f" | wc -l) -eq 1 ]] && echo "_avx512f" || echo "")
          HAS_AVX2=$([[ $(lscpu | grep "avx2" | wc -l) -eq 1 ]] && echo "_avx2" || echo "")
          HAS_FMA=$([[ $(lscpu | grep "fma" | wc -l) -eq 1 ]] && echo "_fma" || echo "")
          HAS_AVX=$([[ $(lscpu | grep "avx" | wc -l) -eq 1 ]] && echo "_avx" || echo "")
          VECTOR_EXTENSIONS=${HAS_AVX512F}${HAS_AVX2}${HAS_FMA}${HAS_AVX}
          echo "VECTOR_EXTENSIONS=$VECTOR_EXTENSIONS" >> $GITHUB_ENV
      - name: spack buildcache
        id: spack-buildcache
        uses: actions/cache@v3
        #env:
        #  cache-name: spack-buildcache_
        with:
          path: |
            /spack_buildcache
            /spack_keys
          key: spack-cache-${{ matrix.os }}-${{ matrix.spack-version }}-${{ env.VECTOR_EXTENSIONS }}
          restore-keys: spack-cache-${{ matrix.os }}-${{ matrix.spack-version }}-
      - name: install-spack
        shell: bash
        run: |
          sudo mkdir /spack
          sudo chown -R ${USER}:${USER} /spack
          git clone --depth 1 --branch ${{ matrix.spack-version }}  https://github.com/spack/spack.git /spack
          mkdir /spack/.cache
          mkdir /spack/.tmp
          echo "config:" > /spack/etc/spack/config.yaml
          echo "  install_tree:" >> /spack/etc/spack/config.yaml
          echo "    padded_length: True" >> /spack/etc/spack/config.yaml
          echo "#!/bin/bash" > /spack/share/spack/my-setup-env.sh
          echo "export SPACK_DISABLE_LOCAL_CONFIG=true" >> /spack/share/spack/my-setup-env.sh
          echo "export SPACK_USER_CACHE_PATH=/spack/.cache" >> /spack/share/spack/my-setup-env.sh
          echo "export TMP=/spack/.tmp" >> /spack/share/spack/my-setup-env.sh
          echo ". /spack/share/spack/setup-env.sh" >> /spack/share/spack/my-setup-env.sh
          . /spack/share/spack/my-setup-env.sh
          spack compiler find
          spack repo add /repos
      - if: ${{ steps.spack-buildcache.outputs.cache-hit != 'true' }}
        name: create buildcache keys
        shell: bash
        run: |
          sudo mkdir /spack_buildcache
          sudo chown -R ${USER}:${USER} /spack_buildcache
          sudo mkdir /spack_keys
          sudo chown -R ${USER}:${USER} /spack_keys
          . /spack/share/spack/my-setup-env.sh
          spack gpg create --export-secret /spack_keys/key.private --export /spack_keys/key.public spack-test spacktest@ghex.org
      - name: import keys and add cache
        shell: bash
        run: |
          . /spack/share/spack/my-setup-env.sh
          spack gpg trust /spack_keys/key.private
          spack mirror add mirror /spack_buildcache
          spack buildcache update-index /spack_buildcache
      - name: build-and-test
        shell: bash
        run: |
          . /spack/share/spack/my-setup-env.sh
          spack spec -I hwmalloc@master
          spack install --test=root hwmalloc@master
          spack buildcache push --only dependencies -a -k spack-test /spack_buildcache hwmalloc@master

