name: spack

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build-cpu:
    runs-on: ubuntu-latest
    container: ghcr.io/gridtools/gridtools-base:gcc-9-ucx-mpi
    strategy:
      matrix:
        #os: [ubuntu-22.04]
        python-version: ['3.10']
        #spack-version: ['develop', 'latest_release']
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: install-ghex-org-packages
        run: |
          mkdir /repos
          git clone https://github.com/ghex-org/spack-repos.git /repos
      - name: install-spack
        shell: bash
        run: |
          mkdir /spack
          git clone --depth 1 --branch v0.19.0 https://github.com/spack/spack.git /spack
          echo "making cache dir"
          mkdir /spack/.cache
          mkdir /spack/.tmp
          echo "exporting spack env variables"
          export SPACK_DISABLE_LOCAL_CONFIG=true
          export SPACK_USER_CACHE_PATH=/spack/.cache
          export TMP=/spack/.tmp
          echo "sourcing spack setup"
          . /spack/share/spack/setup-env.sh
          echo "finding compilers"
          spack compiler find
          echo "adding repo"
          spack repo add /repos
      - name: build-and-test
        run: |
          export SPACK_DISABLE_LOCAL_CONFIG=true
          export SPACK_USER_CACHE_PATH=/spack/.cache
          export TMP=/spack/.tmp
          source /spack/share/spack/setup-env.sh
          spack install -v --test=root hwmalloc@master

