name: spack

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build-cpu:
    runs-on: ubuntu-latest
    container: ghcr.io/gridtools/gridtools-base:gcc-9-ucx-mpi
    steps:
      - name: install-ghex-org-packages
        run: |
          mkdir /repos
          git clone https://github.com/ghex-org/spack-repos.git /repos
      - name: install-spack
        run: |
          mkdir /spack
          git clone --depth 1 --branch v0.20.1 https://github.com/spack/spack.git /spack
          mkdir /spack/.cache
          export SPACK_DISABLE_LOCAL_CONFIG=true
          export SPACK_USER_CACHE_PATH=/spack/.cache
          source /spack/share/spack/setup-env.sh
          spack compiler find
          spack repo add /repos
      - name: build-and-test
        run: |
          export SPACK_DISABLE_LOCAL_CONFIG=true
          export SPACK_USER_CACHE_PATH=/spack/.cache
          source /spack/share/spack/setup-env.sh
          spack install -v --test=root hwmalloc@master

